name: goreferrer

up:
  - go: 1.14.7
  - custom:
      name: Setup go dependencies
      meet: echo 'go mod failed to install packages'; false
      met?: go mod download

commands:
  test:
    run: go get -race -t ./... && go test -race ./...
    desc: 'run unit tests'
